repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: git://github.com/igorshubovych/markdownlint-cli
    rev: v0.22.0
    hooks:
      - id: markdownlint

  - repo: local
    hooks:
      - id: orb.yml
        name: validate orb.yml
        language: system
        entry: circleci orb validate orb.yml
        files: 'orb\.yml'
        pass_filenames: false
