version: 2.1

description: >
  Use to check for ECR image scan findings

display:
  home_url: https://truss.works/
  source_url: https://github.com/trussworks/ecr-image-scan-findings

commands:
  scan:
    description: Scans then outputs the findings
    parameters:
      aws-role-arn:
        type: string
        description: The arn of the aws role able to use ecr
      aws-role-session-name:
        type: string
        description: The name of the role's session name
      ecr-repository-name:
        type: string
        description: The name of the ECR repository for the image that will be scanned
        default: ""
    steps:
      - run:
          command: |
            if [[ -n << parameters.ecr-repository-name >> ]]; then
              temp_role=$(aws sts assume-role \
                      --role-arn << parameters.aws-role-arn >> \
                      --role-session-name << parameters.aws-role-session-name >> )
              export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId | xargs)
              export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey | xargs)
              export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken | xargs)
            fi

            get_findings() {
                findings=$(aws ecr describe-image-scan-findings --repository-name "<< parameters.ecr-repository-name >>" --image-id "imageTag=\"$CIRCLE_SHA1\"")
                echo "${findings}" | jq .
                echo
                status=$(echo "${findings}" | jq -r ".imageScanStatus.status")
                numberOfFindings=$(echo "${findings}" | jq -r ".imageScanFindings.findings | length")
            }

            # Get the results of the scan or wait until they are ready
            get_findings
            while [[ "${status}" == "IN_PROGRESS" ]]; do
                sleep 15
                get_findings
            done

            if [[ "${status}" != *COMPLETE* ]]; then
                echo "Scan does not appear COMPLETE"
                exit 1
            fi

            if [[ "${numberOfFindings}" -gt 0 ]]; then
                echo "Scan found ${numberOfFindings} findings!"
                exit 1
            fi

jobs:
  scan:
    parameters:
      aws-role-arn:
        type: string
        description: The arn of the aws role able to use ecr
      aws-role-session-name:
        type: string
        description: The name of the role's session name
      ecr-repository-name:
        type: string
        description: The name of the ECR repository for the image that will be scanned
        default: ""
    executor: trussworks-circleci-docker-primary
    steps:
      - scan:
          aws-role-arn: << parameters.aws-role-arn >>
          aws-role-session-name: << parameters.aws-role-session-name >>
          ecr-repository-name: << parameters.ecr-repository-name >>

executors:
  trussworks-circleci-docker-primary:
    docker:
      - image: trussworks/circleci-docker-primary:e66fbea875bcb788b29b1b5f59142e8231961ec5
