version: 2.1

description: >
  Use to check for ECR image scan findings

display:
  home_url: https://truss.works/
  source_url: https://github.com/trussworks/ecr-image-scan-findings

commands:
  scan:
    description: Scans then outputs the findings
<<<<<<< Updated upstream
=======
    parameters:
      aws-role-arn:
        type: string
        description: The arn of the aws role able to use ecr
      aws-role-session-name:
        type: string
        description: The name of the role's session name
      image-name:
        type: string
        description: The name of the image
>>>>>>> Stashed changes
    steps:
      - run:
          command: |
            get_findings() {
                findings=$(aws ecr describe-image-scan-findings --repository-name "<< parameters.image-name >>" --image-id "imageTag=\"$CIRCLE_SHA1\"")
                echo "${findings}" | jq .
                echo
                status=$(echo "${findings}" | jq -r ".imageScanStatus.status")
                numberOfFindings=$(echo "${findings}" | jq -r ".imageScanFindings.findings | length")
            }

            # Get the results of the scan or wait until they are ready
            get_findings
            while [[ "${status}" == "IN_PROGRESS" ]]; do
                sleep 15
                get_findings
            done

            if [[ "${status}" != *COMPLETE* ]]; then
                echo "Scan does not appear COMPLETE"
                exit 1
            fi

            if [[ "${numberOfFindings}" -gt 0 ]]; then
                echo "Scan found ${numberOfFindings} findings!"
                exit 1
            fi

jobs:
  scan:
    parameters:
      aws-role-arn:
        type: string
        description: The arn of the aws role able to use ecr
      aws-role-session-name:
        type: string
        description: The name of the role's session name
      image-name:
        type: string
        description: The name of the image
    executor: trussworks-circleci-docker-primary
    steps:
      - scan:
          aws-role-arn: << parameters.aws-role-arn >>
          aws-role-session-name: << parameters.aws-role-session-name >>
          image-name: << parameters.image-name >>

executors:
  trussworks/circleci-docker-primary:
    docker:
      - image: trussworks/circleci-docker-primary:e66fbea875bcb788b29b1b5f59142e8231961ec5
